/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* define if the GLU header should be included as GL/glu.h */
/* #undef HAVE_GL_GLU_H */

/* Define this to use OpenGL widget from <GL/GLwDrawA.h> */
/* #undef HAVE_GL_GLWDRAWA_H */

/* Define this to use OpenGL widget from <GL/GLwMDrawA.h> */
/* #undef HAVE_GL_GLWMDRAWA_H */

/* define if the GL header should be included as GL/gl.h */
#define HAVE_GL_GL_H 1

/* Define to enable use of Inventor feature */
#define HAVE_HARDCOPY 1

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* define if the GLU header should be included as OpenGL/glu.h */
/* #undef HAVE_OPENGL_GLU_H */

/* define if the GL header should be included as OpenGL/gl.h */
/* #undef HAVE_OPENGL_GL_H */

/* define if pthread's struct timespec uses nsecs and not usecs */
/* #undef HAVE_PTHREAD_TIMESPEC_NSEC */

/* Define to enable explicit use of simage library */
/* #undef HAVE_SIMAGE_LIBRARY */

/* Define to enable use of SimVoleon library */
/* #undef HAVE_SIMVOLEON_LIBRARY */

/* Define to enable use of SmallChange library */
/* #undef HAVE_SMALLCHANGE_LIBRARY */

/* Define to enable use of the Open Inventor SoBumpMap node */
#define HAVE_SOBUMPMAP 1

/* Define to enable use of the Open Inventor SoBumpMapTransform node */
#define HAVE_SOBUMPMAPTRANSFORM 1

/* Define to enable use of Inventor feature */
#define HAVE_SOCOMPONENT_SETFULLSCREEN 1

/* Define to enable use of the Open Inventor SoExtSelection node */
#define HAVE_SOEXTSELECTION 1

/* Define to enable use of Inventor feature */
#define HAVE_SOEXTSELECTION_LASSOMODE 1

/* Define to enable use of Inventor feature */
#define HAVE_SOGLRENDERACTION_SORTED_OBJECT_SORTED_TRIANGLE_BLEND 1

/* Define to enable use of Inventor feature */
#define HAVE_SOGUIGLWIDGET_ACCUMULATIONBUFFER 1

/* Define to enable use of the Open Inventor SoImage node */
#define HAVE_SOIMAGE 1

/* Define to enable use of Inventor feature */
#define HAVE_SOINTERSECTIONDETECTIONACTION 1

/* Define to enable use of the Open Inventor SoMarkerSet node */
#define HAVE_SOMARKERSET 1

/* Define to enable use of the Open Inventor SoPolygonOffset node */
#define HAVE_SOPOLYGONOFFSET 1

/* Define to enable use of the Open Inventor SoSceneTexture2 node */
#define HAVE_SOSCENETEXTURE2 1

/* Define to enable use of the Open Inventor SoTextureScalePolicy node */
#define HAVE_SOTEXTURESCALEPOLICY 1

/* Define to enable use of the Open Inventor SoTextureUnit node */
#define HAVE_SOTEXTUREUNIT 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to enable use of Inventor feature */
#define HAVE_VIEWER_QUADBUFFER_STEREO 1

/* Define to enable use of Inventor feature */
#define HAVE_VIEWER_STEREO_VIEWING 1

/* Define to 1 if you have the <windows.h> header file. */
#define HAVE_WINDOWS_H 1

/* Define this to use OpenGL widget from <X11/GLw/GLwDrawA.h> */
/* #undef HAVE_X11_GLW_GLWDRAWA_H */

/* Define this to use OpenGL widget from <X11/GLw/GLwMDrawA.h> */
/* #undef HAVE_X11_GLW_GLWMDRAWA_H */

/* Name of package */
#define PACKAGE "examples"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.0.0"

/* Define this to the Xt/Motif OpenGL widget class to use */
/* #undef XT_GLWIDGET */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */
